Interview Report
sonwonjae/HDM-Project pull request #25
Opened 2021-11-04 12:46 UTC by kkdd0757

1. CSS 스타일링 편집
2. JS 변수명 변경

2021-11-04 16:44 UTC, sonwonjae requested changes

2021-11-04 16:44 UTC, sonwonjae commented on src/js/frontend/report.js
> +  const { data } = await axios.get('/interview', { maxBodyLength: Infinity });
router.interview로 고쳐주세요

2021-11-05 00:50 UTC, kkdd0757 commented on src/js/frontend/report.js
> +  const { data } = await axios.get('/interview', { maxBodyLength: Infinity });
#25 고쳤습니다. 갑사합니다 :))

2021-11-05 00:51 UTC, sonwonjae commented on src/js/frontend/report.js
> +  const { data } = await axios.get('/interview', { maxBodyLength: Infinity });
👍

2021-11-05 00:51 UTC, merged